version: '3.7'

services:
  postgres:
    container_name: 'webedia-postgres'
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my_pass
